# =================================================================
# FICHIER DE CONFIGURATION NETLIFY COMPLET ET CORRIGÉ
# Ce fichier remplace et fusionne _redirects et _headers.
# =================================================================

# --- Paramètres de Build ---
[build]
  # Le dossier racine de votre projet contient tous les fichiers à publier.
  publish = "."

[build.environment]
  # Spécifie la version de Node.js si nécessaire pour le build.
  NODE_VERSION = "18"

# --- Optimisation des Fichiers (Assets) ---
# Netlify va automatiquement minifier et regrouper vos CSS et JS.
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  # Active les "jolies URL" (ex: /about au lieu de /about.html)
  pretty_urls = true

# =================================================================
# REDIRECTIONS
# Règle unique et robuste pour un site "Single Page".
# =================================================================

[[redirects]]
  # Toutes les requêtes de pages qui n'existent pas...
  from = "/*"
  # ...sont renvoyées vers votre page principale.
  to = "/index.html"
  # Le status 200 indique que c'est une réécriture, pas une erreur.
  status = 200
  # Note : Votre page 404.html sera automatiquement utilisée par Netlify 
  # pour les fichiers non trouvés (ex: une image manquante), 
  # ce qui est le comportement souhaité.

# =================================================================
# EN-TÊTES HTTP (SÉCURITÉ ET CACHE)
# =================================================================

# --- En-têtes de sécurité pour toutes les pages ---
[[headers]]
  for = "/*"
  [headers.values]
    # Protection contre le clickjacking.
    X-Frame-Options = "DENY"
    # Empêche le navigateur de deviner le type de contenu.
    X-Content-Type-Options = "nosniff"
    # Active la protection XSS sur les anciens navigateurs.
    X-XSS-Protection = "1; mode=block"
    # Contrôle les informations envoyées dans le Referer.
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Politique de Sécurité de Contenu (CSP)
    # Gardée telle que vous l'avez définie, elle est excellente.
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://fonts.gstatic.com;"

# --- En-têtes de cache pour les assets statiques ---
# Indique au navigateur de garder les images en cache pour une très longue durée.
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

# --- En-têtes spécifiques pour les autres fichiers ---
[[headers]]
  for = "/ai-summary.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=3600" # Cache de 1 heure