# =================================================================
# FICHIER DE CONFIGURATION NETLIFY FINAL ET CORRIGÉ
# =================================================================

# --- Paramètres de Build ---
[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# --- Optimisation des Fichiers (Assets) ---
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true

# =================================================================
# REDIRECTIONS
# Règle UNIQUE et essentielle pour un site "Single Page" (SPA).
# Elle garantit que toutes les routes sont gérées par index.html,
# tout en laissant Netlify gérer les vraies erreurs 404 pour les fichiers physiques manquants.
# =================================================================

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# =================================================================
# EN-TÊTES HTTP (SÉCURITÉ ET CACHE)
# =================================================================

# --- En-têtes de sécurité pour toutes les pages ---
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://fonts.gstatic.com;"

# --- En-têtes de cache pour les assets statiques ---
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

# --- En-têtes spécifiques pour les autres fichiers ---
[[headers]]
  for = "/ai-summary.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=3600"